AWSTemplateFormatVersion: "2010-09-09"
Description: opencode-cloud quick deploy (ALB + ACM + private EC2 + cloud-init)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Required"
        Parameters:
          - DomainName
          - HostedZoneId
      - Label:
          default: "Advanced: Instance"
        Parameters:
          - InstanceType
          - RootVolumeSize
          - KeyPairName
          - OpencodeUsername
      - Label:
          default: "Advanced: Networking"
        Parameters:
          - UseExistingVpc
          - ExistingVpcId
          - ExistingPublicSubnetIdA
          - ExistingPublicSubnetIdB
          - AllowSsh
      - Label:
          default: "Advanced: AMI"
        Parameters:
          - UbuntuAmiId

Parameters:
  DomainName:
    Type: String
    # TODO: Elaborate on this; must they use a domain they already own or can they use a brand new one?
    MinLength: 3
    MaxLength: 253
    AllowedPattern: "^(?=.{1,253}$)(?!-)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$"
    ConstraintDescription: "Provide a valid FQDN (e.g., opencode.example.com)."
    Description: "Fully-qualified domain name for HTTPS (ACM certificate validation required). This should be compatible with the HostedZone you provided. For example, if the HostedZone is 'example.com', the DomainName could be 'opencode.example.com'."
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: "Route53 hosted zone ID for DNS validation. This should be compatible with the DomainName you provided. For example, if the DomainName is 'opencode.example.com', the HostedZoneId has to be the ID of the 'example.com' hosted zone."
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3a.micro
      - t3a.small
      - t3a.medium
      - t3a.large
    Description: "EC2 instance type for opencode-cloud. Smaller sizes (t3/t3a micro or small) may be unstable under load."
  RootVolumeSize:
    Type: Number
    Default: 50
    MinValue: 16
    Description: "Root EBS volume size in GiB."
  KeyPairName:
    Type: String
    Default: ""
    Description: "Optional EC2 key pair name (not ID) for SSH access (credentials are available in Secrets Manager)."
  OpencodeUsername:
    Type: String
    Default: opencode
    Description: "Initial opencode username created during provisioning. This is in addition to the default ubuntu user which has no password but is only accessible via SSH."
  UseExistingVpc:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "Use existing VPC/subnets instead of creating a new VPC."
  ExistingVpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-00000000
    Description: "Existing VPC ID (required if UseExistingVpc=true)."
  ExistingPublicSubnetIdA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-00000000
    Description: "Existing public subnet ID in AZ A (required if UseExistingVpc=true)."
  ExistingPublicSubnetIdB:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-00000000
    Description: "Existing public subnet ID in AZ B (required if UseExistingVpc=true)."
  AllowSsh:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "Allow SSH access to the instance. When false, access is via AWS Systems Manager (SSM) Session Manager, or via other VPC paths (bastion/VPN)."
  UbuntuAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id"
    Description: "Ubuntu 24.04 LTS AMI (SSM public parameter)."

Conditions:
  UseExistingVpcCondition: !Equals [!Ref UseExistingVpc, "true"]
  CreateVpc: !Equals [!Ref UseExistingVpc, "false"]
  UseKeyPair: !Not [!Equals [!Ref KeyPairName, ""]]
  AllowSshCondition: !Equals [!Ref AllowSsh, "true"]

Rules:
  ExistingVpcRequired:
    RuleCondition: !Equals [!Ref UseExistingVpc, "true"]
    Assertions:
      - Assert: !Not [!Equals [!Ref ExistingVpcId, "vpc-00000000"]]
        AssertDescription: "ExistingVpcId must be a real VPC ID when UseExistingVpc=true."
      - Assert: !Not [!Equals [!Ref ExistingPublicSubnetIdA, "subnet-00000000"]]
        AssertDescription: "ExistingPublicSubnetIdA must be a real subnet ID when UseExistingVpc=true."
      - Assert: !Not [!Equals [!Ref ExistingPublicSubnetIdB, "subnet-00000000"]]
        AssertDescription: "ExistingPublicSubnetIdB must be a real subnet ID when UseExistingVpc=true."
Resources:
  CredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "opencode-cloud/${AWS::StackName}/credentials"
      Description: "opencode-cloud bootstrap credentials"

  Vpc:
    Type: AWS::EC2::VPC
    Condition: CreateVpc
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: CreateVpc
    Properties:
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-igw

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-public-a

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-public-b

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.10.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-private-a

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-private-b

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    Condition: CreateVpc
    DependsOn: VpcGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateVpc
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateVpc
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

  NatEip:
    Type: AWS::EC2::EIP
    Condition: CreateVpc
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Condition: CreateVpc
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-nat

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Condition: CreateVpc
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: opencode-cloud-quick-private-rt

  PrivateRoute:
    Type: AWS::EC2::Route
    Condition: CreateVpc
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateVpc
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateVpc
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: opencode-cloud ALB security group
      VpcId: !If [UseExistingVpcCondition, !Ref ExistingVpcId, !Ref Vpc]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: opencode-cloud instance security group
      VpcId: !If [UseExistingVpcCondition, !Ref ExistingVpcId, !Ref Vpc]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref AlbSecurityGroup
        - !If
          - AllowSshCondition
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - !Ref "AWS::NoValue"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: opencode-credentials-secret-write
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:PutSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Ref CredentialsSecret
              - Effect: Allow
                Action:
                  - cloudformation:SignalResource
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*"
      Path: /

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${AWS::StackName}-alb"
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets: !If
        - UseExistingVpcCondition
        - - !Ref ExistingPublicSubnetIdA
          - !Ref ExistingPublicSubnetIdB
        - - !Ref PublicSubnetA
          - !Ref PublicSubnetB

  DomainAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: false

  OpencodeTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AWS::StackName}-web"
      Port: 3000
      Protocol: HTTP
      VpcId: !If [UseExistingVpcCondition, !Ref ExistingVpcId, !Ref Vpc]
      TargetType: instance
      HealthCheckPath: /health
      Matcher:
        HttpCode: "200-399"
      Targets:
        - Id: !Ref OpencodeInstance
          Port: 3000


  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref OpencodeTargetGroup


  OpencodeInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M
        Count: 1
    Properties:
      ImageId: !Ref UbuntuAmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !If [UseKeyPair, !Ref KeyPairName, !Ref "AWS::NoValue"]
      Tags:
        - Key: Name
          Value: !Sub "opencode-cloud-${AWS::StackName}"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref RootVolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
      NetworkInterfaces:
        - DeviceIndex: "0"
          AssociatePublicIpAddress: !If [UseExistingVpcCondition, true, false]
          SubnetId: !If
            - UseExistingVpcCondition
            - !Ref ExistingPublicSubnetIdA
            - !Ref PrivateSubnetA
          GroupSet:
            - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #cloud-config
            apt:
              conf: |
                Acquire::ForceIPv4 "true";
            package_update: true
            package_upgrade: false
            packages:
              - build-essential
              - curl
              - docker.io
              - jq
              - libssl-dev
              - pkg-config
            write_files:
              - path: /etc/opencode-cloud/stack.env
                permissions: "0600"
                content: |
                  OPENCODE_IMAGE=ghcr.io/prizz/opencode-cloud-sandbox:latest
                  OPENCODE_CONTAINER_NAME=opencode-cloud-sandbox
                  OPENCODE_USERNAME=${OpencodeUsername}
                  OPENCODE_DOMAIN_URL=https://${DomainName}
                  OPENCODE_ALB_URL=https://${ApplicationLoadBalancer.DNSName}
                  OPENCODE_CREDENTIALS_SECRET_ARN=${CredentialsSecret}
                  AWS_REGION=${AWS::Region}
              - path: /etc/motd
                permissions: "0644"
                content: |
                  opencode-cloud ready. (cloudformation)
                  init logs:
                    /var/log/opencode-cloud-setup.log
                    /var/log/cloud-init-output.log
                    /var/log/cloud-init.log
                    /var/log/cfn-init.log
                    /var/log/cfn-init-cmd.log
                  Username: ${OpencodeUsername}
                  opencode: https://${DomainName}
                  Credentials secret: ${CredentialsSecret}
                  Fetch credentials:
                    aws secretsmanager get-secret-value --region ${AWS::Region} \
                      --secret-id ${CredentialsSecret} \
                      --query SecretString --output text
                  Container shell:
                    docker ps -q --filter "name=opencode-cloud-sandbox"
                    docker exec -it opencode-cloud-sandbox /bin/bash
              - path: /usr/local/bin/opencode-cloud-setup.sh
                permissions: "0755"
                content: |
                  #!/usr/bin/env bash
                  set -euo pipefail
                  OPENCODE_SETUP_BASE_URL="https://raw.githubusercontent.com/pRizz/opencode-cloud/main/scripts/provisioning"
                  OPENCODE_SETUP_DEST="/usr/local/bin"

                  fetch_script() {
                    local name="$1"
                    local tmp_path

                    tmp_path="$(mktemp)"
                    curl -sSfL "$OPENCODE_SETUP_BASE_URL/$name" -o "$tmp_path"
                    install -m 0755 "$tmp_path" "$OPENCODE_SETUP_DEST/$name"
                    chown root:root "$OPENCODE_SETUP_DEST/$name"
                    rm -f "$tmp_path"
                  }

                  fetch_script "opencode-cloud-setup.sh"
                  fetch_script "opencode-cloud-setup-cloudformation.sh"
                  fetch_script "opencode-cloud-setup-cloud-init.sh"

                  export OPENCODE_STACK_NAME="${AWS::StackName}"
                  export OPENCODE_SIGNAL_RESOURCE="OpencodeInstance"
                  exec "$OPENCODE_SETUP_DEST/opencode-cloud-setup-cloudformation.sh"
            runcmd:
              - [bash, -lc, "/usr/local/bin/opencode-cloud-setup.sh"]

Outputs:
  OpencodeUrl:
    Description: "Primary opencode URL (requires DNS + ACM validation)."
    Value: !Sub "https://${DomainName}"
  AlbDnsName:
    Description: "ALB DNS name (useful for debugging before DNS cutover)."
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  CertificateArn:
    Description: "ACM certificate ARN."
    Value: !Ref Certificate
  InstanceId:
    Description: "EC2 instance ID."
    Value: !Ref OpencodeInstance
  InstanceConsoleUrl:
    Description: "EC2 instance in AWS console."
    Value: !Sub "https://console.aws.amazon.com/ec2/v2/home?region=${AWS::Region}#InstanceDetails:instanceId=${OpencodeInstance}"
  NatElasticIp:
    Condition: CreateVpc
    Description: "NAT Gateway Elastic IP (created with new VPC)."
    Value: !GetAtt NatEip.PublicIp
  NatElasticIpAllocationId:
    Condition: CreateVpc
    Description: "NAT Gateway Elastic IP allocation ID."
    Value: !GetAtt NatEip.AllocationId
  VpcId:
    Description: "VPC ID (created or provided)."
    Value: !If [UseExistingVpcCondition, !Ref ExistingVpcId, !Ref Vpc]
  PublicSubnets:
    Description: "Public subnet IDs used by the ALB."
    Value: !If
      - UseExistingVpcCondition
      - !Join [",", [!Ref ExistingPublicSubnetIdA, !Ref ExistingPublicSubnetIdB]]
      - !Join [",", [!Ref PublicSubnetA, !Ref PublicSubnetB]]
  InstanceSubnet:
    Description: "Subnet ID used by the instance."
    Value: !If
      - UseExistingVpcCondition
      - !Ref ExistingPublicSubnetIdA
      - !Ref PrivateSubnetA
  CredentialsSecretArn:
    Description: "Secrets Manager ARN for generated credentials."
    Value: !Ref CredentialsSecret
